title: Your ad here.
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jpstroop.info" # the base hostname & protocol for your site
twitter_username: jpstroop
github_username: jpstroop

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
